export const metadata = {
  title: 'teste',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>header</h1>
        </header>
        {children}
        <footer>
          <p>footer</p>
        </footer>
      </body>
    </html>
  )
}
